# Players API

POST http://localhost:80/player/new
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache

{
  "name": "Player"
}

###

GET http://localhost:80/player/stats
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 30722a30-63c0-cd92-63c4-e53a28a7b572

###

POST http://localhost:80/player/move
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 30722a30-63c0-cd92-63c4-e53a28a7b572

[
  {
    "x": 1,
    "y": 1
  }
]

###

GET http://localhost:80/player/interact
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 30722a30-63c0-cd92-63c4-e53a28a7b572

###

POST http://localhost:80/player/interact
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
PlayerID: 30722a30-63c0-cd92-63c4-e53a28a7b572

{
  "item_id": "2b86fbf4-a681-8812-4f44-663f04399661"
}

###

GET http://localhost:80/world
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 99af1d60-4320-8379-a064-653a87a69737

###