# Players API

POST http://localhost:8042/player/new
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache

{
  "name": "TestPlayer"
}

###

GET http://localhost:8042/player/stats
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 4017580f-e22d-3dba-bbe7-107fbb60b7eb

###

POST http://localhost:8042/player/move
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID:  4017580f-e22d-3dba-bbe7-107fbb60b7eb

[
  {
    "x": 7,
    "y": 12
  }
]

###

GET http://localhost:8042/player/interact
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 4017580f-e22d-3dba-bbe7-107fbb60b7eb

###

POST http://localhost:8042/player/interact
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
PlayerID: 4017580f-e22d-3dba-bbe7-107fbb60b7eb

{
  "item_id": "4017580f-e22d-3dba-bbe7-107fbb60b7eb"
}

###

GET http://localhost:8042/world
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 4017580f-e22d-3dba-bbe7-107fbb60b7eb

###