# Players API

POST http://localhost:80/player/new
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache

{
  "name": "Player2"
}

###

GET http://localhost:80/player/stats
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: d9c3beac-3206-c411-336d-41651b549729

###

POST http://localhost:80/player/move
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: a35738dd-7446-f105-6d51-719042aec377

[
  {
    "x": 3,
    "y": 1
  },
  {
    "x": 3,
    "y": 2
  }
]

###

GET http://localhost:80/player/interact
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 99af1d60-4320-8379-a064-653a87a69737

###

POST http://localhost:80/player/interact?item_id=f5da2664-9d79-1ae6-f3a2-ea55b5a40105
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
PlayerID: 99af1d60-4320-8379-a064-653a87a69737

###

GET http://localhost:80/world
Accept: */*
Content-Type: application/json;utf-8
Cache-Control: no-cache
# ID must be used when you generated new player
PlayerID: 99af1d60-4320-8379-a064-653a87a69737

###